project:
  type: website
  output-dir: _site
  
website:
  title: "CHQ Daily Update"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

# GitHub Pages specific settings
execute:
  freeze: auto