project:
  type: website
  output-dir: _site
  
website:
  title: "CombatAddictionCHQ.com"
  navbar:
    left:
      - text: "![](County_outline.png){width=75}"
        href: index.qmd
#        text: Home
#      - about.qmd
#    left:
#        href: index.qmd

# GitHub Pages specific settings
execute:
  freeze: auto