project:
  type: website
  output-dir: _site

website:
  title: "The Dashboard"
  search: false
  navbar:
    left:             # 4 spaces indentation
      - text: "![](County_outline.png){.responsive-logo}"  # 6 spaces indentation
        href: index.qmd                          # 6 spaces indentation, aligned with text:
#       html: true
# text: Home
# - about.qmd
# left:
# href: index.qmd

format:
  html:
    css: styles.css
    include-in-header: 
      - text: |
          <style>
            :root {
              --title-base-size: 2rem;
              --logo-base-size: 75px;
            }
          </style>

execute:
  freeze: auto