---
title: "Drug-related Arrests and Possible Overdoses"
format:
  html:
    embed-resources: true
project:
  output-dir: "E:/EMS_calls/News_searches/GitHub/CHQ_Report_GitHub_Actions/twentyandchange.github.io/CHQ_Report_W-Tba4YQG"
editor: visual
warning: false
execute:
  warning: false
  message: false
include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "favicon_1.svg" />
---

::: callout-note
### NOT FOR CIRCULATION
:::

------------------------------------------------------------------------

### A summary compilation for the 7 days ending `r format(Sys.Date(), "%B %e, %Y")`

------------------------------------------------------------------------

## Published news articles: {#news}

```{r}
#| echo: false
#| warning: false
#| message: false
library(readxl)

# Import your Excel file
combined_results <- read_excel("E:/EMS_calls/News_searches/GitHub/CHQ_Report_GitHub_Actions/twentyandchange.github.io/CHQ_Report_W-Tba4YQG/Combined_results.xlsx", 
                               sheet = "Sheet1",  # Specify sheet name or number
                               range = NULL,      # Optional: specific cell range
                               col_names = TRUE)  # First row contains column names

# Now combined_results is available for use throughout the document
```

```{r}
#| echo: false
#| warning: false
#| message: false
#| output: asis

library(htmltools)

cat("
<ul>
")
for(i in 1:nrow(combined_results)) {
  cat(paste0("  <li><a href=\"", combined_results$Link[i], "\" target=\"_blank\">", combined_results$Story_title[i], "</a></li>\n"))
}
cat("</ul>
")
```

######## *(Note: "\_\_ keyword references (WJTN)" refers to the number of drug-related terms present in that news posting.)*

------------------------------------------------------------------------

## EMS dispatches - possible overdoses: {#ods}

```{r}
#| echo: false
#| warning: false
#| message: false

library(sf)
library(leaflet)

# Example: Read a GeoJSON file (replace with your data)
shapefile <- st_read("E:/EMS_calls/News_searches/GitHub/CHQ_Report_GitHub_Actions/twentyandchange.github.io/CHQ_Report_W-Tba4YQG/output_points.shp", quiet = TRUE)

# Create an interactive Leaflet map with popups
leaflet() %>%
  addTiles() %>%
  addMarkers(data = shapefile,
             popup = ~paste("", Address, "<br>","<br>", 
                   "", Dscrptn, "<br>","<br>",
                   "", Dt_nd_t))

```
