# --- Configuration ---
# Set the full path to the directory containing the .qmd file and Git repo
repo_dir <- "E:/EMS_calls/News_searches/GitHub/CHQ_Report_GitHub_Actions/twentyandchange.github.io/CHQ_Report_W-Tba4YQG" 
# Set the name of the Quarto file
qmd_file <- "index.qmd" 

# Set the expected name(s) of the output file(s) generated by Quarto
output_files <- paste0(tools::file_path_sans_ext(qmd_file), c("index.html", "search.json")) 


# Git configuration
commit_message <- paste("Automated render and update:", Sys.time())
remote_name <- "origin" # Usually "origin"
branch_name <- "main"   # Or "master", or your default branch

# --- Script Logic ---
library(gert) # Load the gert package

# Function for logging messages
log_message <- function(msg) {
  timestamp_msg <- paste(Sys.time(), "-", msg)
  print(timestamp_msg)
  # Optional: Append to a log file
  # cat(timestamp_msg, "\n", file = file.path(repo_dir, "automation.log"), append = TRUE)
}

tryCatch({
  # 1. Set Working Directory (Important!)
  log_message("Setting working directory...")
  setwd(repo_dir)
  
  # 2. Render the Quarto Document
  log_message(paste("Rendering", qmd_file, "..."))
  # Ensure the 'quarto' R package is installed if using this function
  quarto::quarto_render(qmd_file) 
  log_message("Quarto rendering completed.")
  
  # 3. Git Operations using gert
  log_message("Starting Git operations...")
  
  # Check status - find which output files actually changed or were created
  status <- git_status(repo = repo_dir)
  files_to_add <- intersect(output_files, status$file) # Only add expected outputs that appear in status
  
  if (length(files_to_add) > 0) {
    log_message(paste("Adding files to Git:", paste(files_to_add, collapse=", ")))
    git_add(files = files_to_add, repo = repo_dir)
    
    log_message("Committing changes...")
    git_commit(message = commit_message, repo = repo_dir)
    log_message("Commit successful.")
    
    log_message(paste("Pushing changes to", remote_name, "/", branch_name, "..."))
    # Ensure authentication (SSH keys recommended) is set up!
    git_push(remote = remote_name, set_upstream = FALSE, repo = repo_dir, verbose = TRUE) 
    log_message("Push successful.")
    
  } else {
    log_message("No changes detected in output files to commit.")
  }
  
  log_message("Script finished successfully.")
  
}, error = function(e) {
  # Log the error
  error_message <- paste("Error during script execution:", e$message)
  log_message(error_message)
  # Consider writing the error to a specific error log file
  # cat(error_message, "\n", file = file.path(repo_dir, "automation_error.log"), append = TRUE) 
  stop(e) # Re-throw the error so Task Scheduler knows it failed
})
