on:
  workflow_dispatch: # Allows manual triggering from Actions tab
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push to gh-pages branch
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0' # Specify desired R version

      # Install system dependencies (keep if needed)
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev libudunits2-dev

      # *** NEW STEP ***
      # Install gert explicitly BEFORE setup-renv runs,
      # so it's available if .Rprofile is sourced by setup-renv's R process.
      - name: Install gert package
        shell: Rscript {0}
        run: |
if (!requireNamespace("gert", quietly = TRUE))
  install.packages("gert", lib = .libPaths()[1], repos = "https://cloud.r-project.org")



      # Use the standard setup-renv action. It should now find gert already
      # installed and proceed to restore other packages from renv.lock.
      - name: Install and cache R dependencies via renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1 # Increment cache version if you need to force a cache refresh

      # Render and publish step
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}